"""
Static catalog of EIA Excel-based publications.

Each publication has a base_url and a list of chapters, each containing
tables. Table URLs are constructed as:
  HTML viewer: {base_url}/table.php?t={id}.html
  Excel file:  {base_url}/xls/{id}.xlsx
"""

ELECTRICITY_ANNUAL = {
    "id": "electricity-annual",
    "title": "Electric Power Annual",
    "base_url": "https://www.eia.gov/electricity/annual",
    "chapters": [
        {
            "number": "1",
            "title": "National Summary Data",
            "tables": [
                {"id": "epa_01_01", "number": "1.1", "title": "Total electric power industry summary statistics"},
                {"id": "epa_01_02", "number": "1.2", "title": "Summary statistics for the United States"},
                {"id": "epa_01_03", "number": "1.3", "title": "Supply and disposition of electricity"},
            ],
        },
        {
            "number": "2",
            "title": "Electricity Sales",
            "tables": [
                {"id": "epa_02_01", "number": "2.1",  "title": "Number of ultimate customers served by sector, by provider"},
                {"id": "epa_02_02", "number": "2.2",  "title": "Sales and direct use of electricity to ultimate customers by sector, by provider"},
                {"id": "epa_02_03", "number": "2.3",  "title": "Revenue from sales of electricity to ultimate customers by sector, by provider"},
                {"id": "epa_02_04", "number": "2.4",  "title": "Average price of electricity to ultimate customers by end-use sector"},
                {"id": "epa_02_05", "number": "2.5",  "title": "Sales of electricity to ultimate customers: Total by end-use sector"},
                {"id": "epa_02_06", "number": "2.6",  "title": "Revenue from sales of electricity to ultimate customers: Total by end-use sector"},
                {"id": "epa_02_07", "number": "2.7",  "title": "Average price of electricity to ultimate customers: Total by end-use sector"},
                {"id": "epa_02_08", "number": "2.8",  "title": "Sales of electricity to ultimate customers by end-use sector, by state"},
                {"id": "epa_02_09", "number": "2.9",  "title": "Revenue from sales of electricity to ultimate customers by end-use sector, by state"},
                {"id": "epa_02_10", "number": "2.10", "title": "Average price of electricity to ultimate customers by end-use sector, by state"},
                {"id": "epa_02_11", "number": "2.11", "title": "Number of ultimate customers by sector"},
                {"id": "epa_02_12", "number": "2.12", "title": "Electric power industry - electricity purchases"},
                {"id": "epa_02_13", "number": "2.13", "title": "Electric power industry - electricity sales for resale"},
                {"id": "epa_02_14", "number": "2.14", "title": "Electric power industry - U.S. electricity imports from and electricity exports to Canada and Mexico"},
            ],
        },
        {
            "number": "3",
            "title": "Net Generation",
            "tables": [
                {"id": "epa_03_01_a", "number": "3.1.A", "title": "Net generation by energy source: Total (all sectors)"},
                {"id": "epa_03_01_b", "number": "3.1.B", "title": "Net generation from renewable sources: Total (all sectors)"},
                {"id": "epa_03_02_a", "number": "3.2.A", "title": "Net generation by energy source: Electric utilities"},
                {"id": "epa_03_02_b", "number": "3.2.B", "title": "Net generation from renewable sources: Electric utilities"},
                {"id": "epa_03_03_a", "number": "3.3.A", "title": "Net generation by energy source: Independent power producers"},
                {"id": "epa_03_03_b", "number": "3.3.B", "title": "Net generation from renewable sources: Independent power producers"},
                {"id": "epa_03_04_a", "number": "3.4.A", "title": "Net generation by energy source: Commercial sector"},
                {"id": "epa_03_04_b", "number": "3.4.B", "title": "Net generation from renewable sources: Commercial sector"},
                {"id": "epa_03_05_a", "number": "3.5.A", "title": "Net generation by energy source: Industrial sector"},
                {"id": "epa_03_05_b", "number": "3.5.B", "title": "Net generation from renewable sources: Industrial sector"},
                {"id": "epa_03_06",   "number": "3.6",   "title": "Net generation by energy source: Residential sector"},
                {"id": "epa_03_07",   "number": "3.7",   "title": "Net generation by state by sector"},
                {"id": "epa_03_08",   "number": "3.8",   "title": "Net generation from coal by state by sector"},
                {"id": "epa_03_09",   "number": "3.9",   "title": "Net generation from petroleum liquids by state by sector"},
                {"id": "epa_03_10",   "number": "3.10",  "title": "Net generation from petroleum coke by state by sector"},
                {"id": "epa_03_11",   "number": "3.11",  "title": "Net generation from natural gas by state by sector"},
                {"id": "epa_03_12",   "number": "3.12",  "title": "Net generation from other gases by state by sector"},
                {"id": "epa_03_13",   "number": "3.13",  "title": "Net generation from nuclear energy by state by sector"},
                {"id": "epa_03_14",   "number": "3.14",  "title": "Net generation from hydroelectric (conventional) power by state by sector"},
                {"id": "epa_03_15",   "number": "3.15",  "title": "Net generation from renewable sources excluding hydroelectric by state by sector"},
                {"id": "epa_03_16",   "number": "3.16",  "title": "Net generation from hydroelectric (pumped storage) power by state by sector"},
                {"id": "epa_03_17",   "number": "3.17",  "title": "Net generation from other energy sources by state by sector"},
                {"id": "epa_03_18",   "number": "3.18",  "title": "Net generation from wind by state by sector"},
                {"id": "epa_03_19",   "number": "3.19",  "title": "Net generation from biomass by state by sector"},
                {"id": "epa_03_20",   "number": "3.20",  "title": "Net generation from geothermal by state by sector"},
                {"id": "epa_03_21",   "number": "3.21",  "title": "Net generation from solar photovoltaic by state by sector"},
                {"id": "epa_03_22",   "number": "3.22",  "title": "Net generation from solar thermal by state by sector"},
                {"id": "epa_03_23",   "number": "3.23",  "title": "Useful thermal output by energy source: Total combined heat and power (all sectors)"},
                {"id": "epa_03_24",   "number": "3.24",  "title": "Useful thermal output by energy source: Electric power sector combined heat and power"},
                {"id": "epa_03_25",   "number": "3.25",  "title": "Useful thermal output by energy source: Commercial sector combined heat and power"},
                {"id": "epa_03_26",   "number": "3.26",  "title": "Useful thermal output by energy source: Industrial sector combined heat and power"},
                {"id": "epa_03_27",   "number": "3.27",  "title": "Gross/net generation by energy storage technology: Total (all sectors)"},
            ],
        },
        {
            "number": "4",
            "title": "Generation Capacity",
            "tables": [
                {"id": "epa_04_01",   "number": "4.1",   "title": "Count of electric power industry power plants, by sector, by predominant energy sources within plant"},
                {"id": "epa_04_02_a", "number": "4.2.A", "title": "Existing net summer capacity by energy source and producer type"},
                {"id": "epa_04_02_b", "number": "4.2.B", "title": "Existing net summer capacity of other renewable sources by producer type"},
                {"id": "epa_04_03",   "number": "4.3",   "title": "Existing capacity by energy source"},
                {"id": "epa_04_04",   "number": "4.4",   "title": "Existing capacity by producer type"},
                {"id": "epa_04_05",   "number": "4.5",   "title": "Planned generating capacity changes, by energy source"},
                {"id": "epa_04_06",   "number": "4.6",   "title": "Capacity additions, retirements and changes by energy source"},
                {"id": "epa_04_07_a", "number": "4.7.A", "title": "Net summer capacity of utility scale units by technology and by state"},
                {"id": "epa_04_07_b", "number": "4.7.B", "title": "Net summer capacity of utility scale units using primarily renewable energy sources and by state"},
                {"id": "epa_04_07_c", "number": "4.7.C", "title": "Net summer capacity of utility scale units using primarily fossil fuels and by state"},
                {"id": "epa_04_08_a", "number": "4.8.A", "title": "Capacity factors for utility scale generators primarily using fossil fuels"},
                {"id": "epa_04_08_b", "number": "4.8.B", "title": "Capacity factors for utility scale generators not primarily using fossil fuel"},
                {"id": "epa_04_08_c", "number": "4.8.C", "title": "Usage factors for utility scale storage generators"},
                {"id": "epa_04_09_a", "number": "4.9.A", "title": "Total capacity of distributed and dispersed generators by technology type"},
                {"id": "epa_04_09_b", "number": "4.9.B", "title": "Total capacity of non net metered distributed generators by technology type and by sector"},
                {"id": "epa_04_10",   "number": "4.10",  "title": "Net metering customers and capacity by technology type, by end use sector"},
                {"id": "epa_04_11",   "number": "4.11",  "title": "Fuel-switching capacity of operable generators reporting natural gas as the primary fuel, by producer type"},
                {"id": "epa_04_12",   "number": "4.12",  "title": "Fuel-switching capacity of operable generators reporting petroleum liquids as the primary fuel, by producer type"},
                {"id": "epa_04_13",   "number": "4.13",  "title": "Fuel-switching capacity of operable generators reporting natural gas as the primary fuel, by type of prime mover"},
                {"id": "epa_04_14",   "number": "4.14",  "title": "Fuel-switching capacity of operable generators reporting natural gas as the primary fuel, by year of initial commercial operation"},
            ],
        },
        {
            "number": "5",
            "title": "Consumption of Fossil Fuels",
            "tables": [
                {"id": "epa_05_01_a", "number": "5.1.A", "title": "Coal: Consumption (thousand tons) for electricity generation by sector"},
                {"id": "epa_05_01_b", "number": "5.1.B", "title": "Coal: Consumption (thousand tons) for useful thermal output by sector"},
                {"id": "epa_05_01_c", "number": "5.1.C", "title": "Coal: Consumption (thousand tons) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_01_d", "number": "5.1.D", "title": "Coal: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_01_e", "number": "5.1.E", "title": "Coal: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_01_f", "number": "5.1.F", "title": "Coal: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_02_a", "number": "5.2.A", "title": "Petroleum liquids: Consumption (thousand barrels) for electricity generation by sector"},
                {"id": "epa_05_02_b", "number": "5.2.B", "title": "Petroleum liquids: Consumption (thousand barrels) for useful thermal output by sector"},
                {"id": "epa_05_02_c", "number": "5.2.C", "title": "Petroleum liquids: Consumption (thousand barrels) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_02_d", "number": "5.2.D", "title": "Petroleum liquids: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_02_e", "number": "5.2.E", "title": "Petroleum liquids: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_02_f", "number": "5.2.F", "title": "Petroleum liquids: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_03_a", "number": "5.3.A", "title": "Petroleum coke: Consumption (thousand tons) for electricity generation by sector"},
                {"id": "epa_05_03_b", "number": "5.3.B", "title": "Petroleum coke: Consumption (thousand tons) for useful thermal output by sector"},
                {"id": "epa_05_03_c", "number": "5.3.C", "title": "Petroleum coke: Consumption (thousand tons) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_03_d", "number": "5.3.D", "title": "Petroleum coke: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_03_e", "number": "5.3.E", "title": "Petroleum coke: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_03_f", "number": "5.3.F", "title": "Petroleum coke: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_04_a", "number": "5.4.A", "title": "Natural gas: Consumption (million cubic feet) for electricity generation by sector"},
                {"id": "epa_05_04_b", "number": "5.4.B", "title": "Natural gas: Consumption (million cubic feet) for useful thermal output by sector"},
                {"id": "epa_05_04_c", "number": "5.4.C", "title": "Natural gas: Consumption (million cubic feet) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_04_d", "number": "5.4.D", "title": "Natural gas: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_04_e", "number": "5.4.E", "title": "Natural gas: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_04_f", "number": "5.4.F", "title": "Natural gas: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_05_d", "number": "5.5.D", "title": "Wood / wood waste biomass: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_05_e", "number": "5.5.E", "title": "Wood / wood waste biomass: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_05_f", "number": "5.5.F", "title": "Wood / wood waste biomass: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_06_a", "number": "5.6.A", "title": "Landfill gas: Consumption (million cubic feet) for electricity generation by sector"},
                {"id": "epa_05_06_b", "number": "5.6.B", "title": "Landfill gas: Consumption (million cubic feet) for useful thermal output by sector"},
                {"id": "epa_05_06_c", "number": "5.6.C", "title": "Landfill gas: Consumption (million cubic feet) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_06_d", "number": "5.6.D", "title": "Landfill gas: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_06_e", "number": "5.6.E", "title": "Landfill gas: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_06_f", "number": "5.6.F", "title": "Landfill gas: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_07_a", "number": "5.7.A", "title": "Biogenic municipal solid waste: Consumption (thousand tons) for electricity generation by sector"},
                {"id": "epa_05_07_b", "number": "5.7.B", "title": "Biogenic municipal solid waste: Consumption (thousand tons) for useful thermal output by sector"},
                {"id": "epa_05_07_c", "number": "5.7.C", "title": "Biogenic municipal solid waste: Consumption (thousand tons) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_07_d", "number": "5.7.D", "title": "Biogenic municipal solid waste: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_07_e", "number": "5.7.E", "title": "Biogenic municipal solid waste: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_07_f", "number": "5.7.F", "title": "Biogenic municipal solid waste: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_08_d", "number": "5.8.D", "title": "Other waste biomass: Consumption (billion Btus) for electricity generation by sector"},
                {"id": "epa_05_08_e", "number": "5.8.E", "title": "Other waste biomass: Consumption (billion Btus) for useful thermal output by sector"},
                {"id": "epa_05_08_f", "number": "5.8.F", "title": "Other waste biomass: Consumption (billion Btus) for electricity generation and useful thermal output by sector"},
                {"id": "epa_05_09",   "number": "5.9",   "title": "Consumption of coal for electricity generation by state by sector"},
                {"id": "epa_05_10",   "number": "5.10",  "title": "Consumption of petroleum liquids for electricity generation by state by sector"},
                {"id": "epa_05_11",   "number": "5.11",  "title": "Consumption of petroleum coke for electricity generation by state by sector"},
                {"id": "epa_05_12",   "number": "5.12",  "title": "Consumption of natural gas for electricity generation by state by sector"},
                {"id": "epa_05_13",   "number": "5.13",  "title": "Consumption of landfill gas for electricity generation by state by sector"},
                {"id": "epa_05_14",   "number": "5.14",  "title": "Consumption of biogenic municipal solid waste for electricity generation by state by sector"},
            ],
        },
        {
            "number": "6",
            "title": "Fossil Fuel Stocks for Electricity Generation",
            "tables": [
                {"id": "epa_06_01", "number": "6.1", "title": "Stocks of coal, petroleum liquids, and petroleum coke: Electric power sector"},
                {"id": "epa_06_02", "number": "6.2", "title": "Stocks of coal, petroleum liquids, and petroleum coke: Electric power sector, by state"},
                {"id": "epa_06_03", "number": "6.3", "title": "Stocks of coal, petroleum liquids, and petroleum coke: Electric power sector, by census division"},
                {"id": "epa_06_04", "number": "6.4", "title": "Stocks of coal by coal rank: Electric power sector"},
            ],
        },
        {
            "number": "7",
            "title": "Receipts, Cost, and Quality of Fossil Fuels",
            "tables": [
                {"id": "epa_07_01", "number": "7.1",  "title": "Receipts, average cost, and quality of fossil fuels for the electric power industry"},
                {"id": "epa_07_02", "number": "7.2",  "title": "Receipts and quality of coal delivered for the electric power industry"},
                {"id": "epa_07_03", "number": "7.3",  "title": "Average quality of fossil fuel receipts for the electric power industry"},
                {"id": "epa_07_04", "number": "7.4",  "title": "Weighted average cost of fossil fuels for the electric power industry"},
                {"id": "epa_07_05", "number": "7.5",  "title": "Receipts, average cost, and quality of fossil fuels: Electric utilities"},
                {"id": "epa_07_06", "number": "7.6",  "title": "Receipts, average cost, and quality of fossil fuels: Electric utilities (continued)"},
                {"id": "epa_07_07", "number": "7.7",  "title": "Receipts, average cost, and quality of fossil fuels: Independent power producers"},
                {"id": "epa_07_08", "number": "7.8",  "title": "Receipts, average cost, and quality of fossil fuels: Independent power producers (continued)"},
                {"id": "epa_07_09", "number": "7.9",  "title": "Receipts, average cost, and quality of fossil fuels: Commercial sector"},
                {"id": "epa_07_10", "number": "7.10", "title": "Receipts, average cost, and quality of fossil fuels: Commercial sector (continued)"},
                {"id": "epa_07_11", "number": "7.11", "title": "Receipts, average cost, and quality of fossil fuels: Industrial sector"},
                {"id": "epa_07_12", "number": "7.12", "title": "Receipts, average cost, and quality of fossil fuels: Industrial sector (continued)"},
                {"id": "epa_07_13", "number": "7.13", "title": "Receipts of coal delivered for electricity generation by state"},
                {"id": "epa_07_14", "number": "7.14", "title": "Receipts of petroleum liquids delivered for electricity generation by state"},
                {"id": "epa_07_15", "number": "7.15", "title": "Receipts of petroleum coke delivered for electricity generation by state"},
                {"id": "epa_07_16", "number": "7.16", "title": "Receipts of natural gas delivered for electricity generation by state"},
                {"id": "epa_07_17", "number": "7.17", "title": "Average cost of coal delivered for electricity generation by state"},
                {"id": "epa_07_18", "number": "7.18", "title": "Average cost of petroleum liquids delivered for electricity generation by state"},
                {"id": "epa_07_19", "number": "7.19", "title": "Average cost of petroleum coke delivered for electricity generation by state"},
                {"id": "epa_07_20", "number": "7.20", "title": "Average cost of natural gas delivered for electricity generation by state"},
                {"id": "epa_07_21", "number": "7.21", "title": "Receipts and quality of coal by rank delivered for electricity generation: Total (all sectors) by state"},
                {"id": "epa_07_22", "number": "7.22", "title": "Receipts and quality of coal by rank delivered for electricity generation: Electric utilities by state"},
                {"id": "epa_07_23", "number": "7.23", "title": "Receipts and quality of coal by rank delivered for electricity generation: Independent power producers by state"},
                {"id": "epa_07_24", "number": "7.24", "title": "Receipts and quality of coal by rank delivered for electricity generation: Commercial sector by state"},
                {"id": "epa_07_25", "number": "7.25", "title": "Receipts and quality of coal by rank delivered for electricity generation: Industrial sector by state"},
            ],
        },
        {
            "number": "8",
            "title": "Electric Power System Characteristics and Performance",
            "tables": [
                {"id": "epa_08_01", "number": "8.1", "title": "Average operating heat rate for selected energy sources"},
                {"id": "epa_08_02", "number": "8.2", "title": "Average tested heat rates by prime mover and energy source"},
                {"id": "epa_08_03", "number": "8.3", "title": "Revenue and expense statistics for major U.S. investor-owned electric utilities"},
                {"id": "epa_08_04", "number": "8.4", "title": "Average power plant operating expenses for major U.S. investor-owned electric utilities"},
            ],
        },
        {
            "number": "9",
            "title": "Environmental Data",
            "tables": [
                {"id": "epa_09_01", "number": "9.1", "title": "Emissions from energy consumption at conventional power plants and combined-heat-and-power plants"},
                {"id": "epa_09_02", "number": "9.2", "title": "Quantity and net summer capacity of operable environmental equipment"},
                {"id": "epa_09_03", "number": "9.3", "title": "Quantity and net summer capacity of operable cooling systems by energy source and cooling system type"},
                {"id": "epa_09_04", "number": "9.4", "title": "Average cost of existing flue gas desulfurization units"},
                {"id": "epa_09_05", "number": "9.5", "title": "Emissions from energy consumption at conventional power plants and combined-heat-and-power plants, by state"},
            ],
        },
        {
            "number": "10",
            "title": "Energy Efficiency, Demand Response and Advanced Meters",
            "tables": [
                {"id": "epa_10_01", "number": "10.1", "title": "Energy efficiency"},
                {"id": "epa_10_02", "number": "10.2", "title": "Energy efficiency - life cycle"},
                {"id": "epa_10_03", "number": "10.3", "title": "Demand response - yearly energy and demand savings"},
                {"id": "epa_10_04", "number": "10.4", "title": "Demand response - program costs"},
                {"id": "epa_10_05", "number": "10.5", "title": "Advanced metering count by technology type"},
            ],
        },
        {
            "number": "11",
            "title": "Distribution System Reliability",
            "tables": [
                {"id": "epa_11_01", "number": "11.1", "title": "Reliability metrics of U.S. distribution system"},
                {"id": "epa_11_02", "number": "11.2", "title": "Reliability metrics using IEEE of U.S. distribution system by state"},
                {"id": "epa_11_03", "number": "11.3", "title": "Reliability metrics using any method of U.S. distribution system by state"},
                {"id": "epa_11_04", "number": "11.4", "title": "SAIDI values of U.S. distribution system by state"},
                {"id": "epa_11_05", "number": "11.5", "title": "SAIFI values of U.S. distribution system by state"},
                {"id": "epa_11_06", "number": "11.6", "title": "CAIDI values of U.S. distribution system by state"},
            ],
        },
        {
            "number": "12",
            "title": "U.S. Territories",
            "tables": [
                {"id": "epa_12_01", "number": "12.1", "title": "Puerto Rico - Number of ultimate customers served, by sector"},
                {"id": "epa_12_02", "number": "12.2", "title": "Puerto Rico - Sales of electricity to ultimate customers, by sector"},
                {"id": "epa_12_03", "number": "12.3", "title": "Puerto Rico - Revenue from sale of electricity to ultimate customers, by sector"},
                {"id": "epa_12_04", "number": "12.4", "title": "Puerto Rico - Average price of electricity to ultimate customers, by sector"},
                {"id": "epa_12_05", "number": "12.5", "title": "American Samoa, by sector"},
                {"id": "epa_12_06", "number": "12.6", "title": "Guam, by sector"},
                {"id": "epa_12_07", "number": "12.7", "title": "Northern Mariana Islands, by sector"},
                {"id": "epa_12_08", "number": "12.8", "title": "Virgin Islands, by sector"},
            ],
        },
        {
            "number": "A",
            "title": "Appendices",
            "tables": [
                {"id": "epa_a_01", "number": "A.1", "title": "Sulfur dioxide uncontrolled emission factors"},
                {"id": "epa_a_02", "number": "A.2", "title": "Nitrogen oxides uncontrolled emission factors"},
                {"id": "epa_a_03", "number": "A.3", "title": "Carbon dioxide uncontrolled emission factors"},
                {"id": "epa_a_04", "number": "A.4", "title": "Nitrogen oxides control technology emissions reduction factors"},
                {"id": "epa_a_05", "number": "A.5", "title": "Unit-of-measure equivalents"},
            ],
        },
    ],
}

# Top-level registry — add future publications here
ALL_PUBLICATIONS = [ELECTRICITY_ANNUAL]


def table_html_url(pub: dict, table_id: str) -> str:
    return f"{pub['base_url']}/table.php?t={table_id}.html"


def table_xlsx_url(pub: dict, table_id: str) -> str:
    return f"{pub['base_url']}/xls/{table_id}.xlsx"
